$entry_background_color = rgba(0, 0, 0, 0.25)
$entry_color = rgba(255, 255, 255, 0.7)
$text_color = rgba(255, 255, 255, 0.85)
$font_family = RecMonoLinear Nerd Font
$font_family_clock = SpaceMono Nerd Font

background {
    path = /home/once/dotfiles/wallpapers/ibm-dark-left-bottom.png

    blur_passes = 0
    brightness = 0.65
}
input-field {
    monitor =
    size = 200, 40
    outline_thickness = 1
    dots_size = 0.16
    dots_spacing = 0.4
    dots_center = true
    outer_color = rgba(255, 255, 255, 0.15)
    inner_color = $entry_background_color
    font_color = $entry_color
    fade_on_empty = true
    placeholder_text = 

    position = 0, 120
    halign = center
    valign = bottom
}
